# Generated by Django 3.0.2 on 2020-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcestatistics',
            name='resource_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
