# Generated by Django 3.0.2 on 2020-01-23 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_resourcestatistics_resource_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(unique=True)),
                ('rating', models.FloatField(default=5)),
                ('views', models.IntegerField(default=0)),
                ('raters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ResourceStatistics',
        ),
    ]
