# Generated by Django 3.0.2 on 2020-01-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_quizanswer_quizquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='text',
        ),
    ]
