# Generated by Django 3.0.2 on 2020-01-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizuserresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuserresult',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
