# Generated by Django 3.0.2 on 2020-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatistics',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
