# Generated by Django 3.0.2 on 2020-01-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilestatistics_karma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilestatistics',
            old_name='karma',
            new_name='points',
        ),
    ]
